# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

require 'benchmark'

def sum_of_even_fibonaccis(limit)
  fibs = [1, 2]
  while fibs[-1] < limit do
    fibs << fibs[-1] + fibs[-2]
  end
  sum = 0
  fibs.each { |fib| sum += fib if fib.even? }
  sum
end

puts "Answer: #{ sum_of_even_fibonaccis(4000000) }"
puts "Time: #{ Benchmark.measure { sum_of_even_fibonaccis(4000000) } }"